Web_NaturalFood/WebApplicationMVC3/Controllers/IngredientesExtrasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Logica;
using ViewModels;

namespace WebApplicationMVC3.Controllers
{
    public class IngredientesExtrasController : Controller
    {
        private LogicaIngredientesExtras _logicaIngredientesExtras;

        public IngredientesExtrasController()
        {
            _logicaIngredientesExtras = new LogicaIngredientesExtras();
        }

            // GET: IngredientesExtras
        public ActionResult Index()
        {
            List<IngredienteExtra> ingredientesextras = _logicaIngredientesExtras.getIngredientesExtras();
            return View(ingredientesextras);
        }

        
        //GET: Crear
        public ActionResult CrearIngredienteExtra()
        {
            return View();
        }

        //POST: Crear Categoria
        [HttpPost]
        public ActionResult CrearIngredienteExtra(CreaIngredienteExtraViewModel ingrediente)
        {

            CreaIngredienteExtraViewModel newIngrediente = new CreaIngredienteExtraViewModel(ingrediente.nombre,ingrediente.precio);

            _logicaIngredientesExtras.InsertaIngredienteExtra(newIngrediente);

            return RedirectToAction("Index");
            //return RedirectToAction("Index");
        }


        // GET: Delete Ingrediente
        public ActionResult DeleteIngredienteExtra(int id)
        {
            _logicaIngredientesExtras.EliminarIngredienteExtra(id);

            return RedirectToAction("Index");
        }

        //GET: Editar 
        public ActionResult EditarIngredienteExtra(int id)
        {
            var entidadIngrediente = _logicaIngredientesExtras.ObtieneIngredienteExtra(id);

            return View(entidadIngrediente);
        }


        //POST: Editar Menu
        [HttpPost]
        public ActionResult EditarIngredienteExtra(IngredienteExtra ingrediente)
        {
            IngredienteExtra newIngrediente = new IngredienteExtra(ingrediente.id_ingrediente, ingrediente.nombre,ingrediente.precio);

            _logicaIngredientesExtras.EditaIngredienteExtra(newIngrediente);

            return RedirectToAction("Index");
        }



    }
}

Web_NaturalFood/WebApplicationMVC3/Controllers/MenuIngredienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Datos;
using Logica;
using ViewModels;

namespace WebApplicationMVC3.Controllers
{
    public class MenuIngredienteController : Controller
    {
        private ConexionBD _conexionbd;
        private LogicaMenuIngrediente _logicaMenuIngrediente;

        public MenuIngredienteController()
        {
            _conexionbd = new ConexionBD();
            _logicaMenuIngrediente = new LogicaMenuIngrediente();
        }



        // GET: Lista Menu Ingredientes
        public ActionResult Index()
        {
            List<MenuIngredienteViewModel> menusIngredientes = _logicaMenuIngrediente.getMenusIngredientes();
    
            return View(menusIngredientes);
        }

        //GET: Crear
        public ActionResult CrearMenuIngrediente()
        {
            return View();
        }


        //POST: Crear Categoria
        [HttpPost]
        public ActionResult CrearMenuIngrediente(CreaMenuIngredienteViewModel menuingrediente)
        {
            string idMenu = Request.Form["dropDownMenus"].ToString();
            //System.Diagnostics.Debug.WriteLine(strDDLValue);
            string idIngrediente = Request.Form["dropDownIngredientes"].ToString();
            //System.Diagnostics.Debug.WriteLine(strDDLValue);
            
            //CreaMenuIngredienteViewModel newMenu = new CreaMenuIngredienteViewModel(menuingrediente.nombreMenu,menuingrediente.nombreIngrediente);

            _logicaMenuIngrediente.InsertaMenuIngrediente(idMenu,idIngrediente);

            return RedirectToAction("Index");
            //return RedirectToAction("Index");
        }


        // GET: Delete Menu
        public ActionResult DeleteMenuIngrediente(int id)
        {
            _logicaMenuIngrediente.EliminarMenuIngrediente(id);

            return RedirectToAction("Index");
        }
    }
}

Web_NaturalFood/WebApplicationMVC3/Controllers/MenuIngredienteExtraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logica;
using ViewModels;

namespace WebApplicationMVC3.Controllers
{
    public class MenuIngredienteExtraController : Controller
    {
        private LogicaMenuIngredienteExtra _logicaMenuIngredienteExtra;

        public MenuIngredienteExtraController()
        {
            _logicaMenuIngredienteExtra = new LogicaMenuIngredienteExtra();
        }

        // GET: MenuIngredienteExtra
        public ActionResult Index()
        {
            List<MenuIngredienteExtraViewModel> menusIngredientes = _logicaMenuIngredienteExtra.getMenusIngredientesExtras();

            return View(menusIngredientes);
        }

        // GET: Delete Menu
        public ActionResult DeleteMenuIngredienteExtra(int id)
        {
            _logicaMenuIngredienteExtra.EliminarMenuIngredienteExtra(id);

            return RedirectToAction("Index");
        }

        //GET: Crear
        public ActionResult CrearMenuIngredienteExtra()
        {
            return View();
        }


        //POST: Crear Categoria
        [HttpPost]
        public ActionResult CrearMenuIngrediente(CreaMenuIngredienteExtraViewModel menuingrediente)
        {
            string idMenu = Request.Form["dropDownMenus"].ToString();
            //System.Diagnostics.Debug.WriteLine(strDDLValue);
            string idIngrediente = Request.Form["dropDownIngredientesExtras"].ToString();
            //System.Diagnostics.Debug.WriteLine(strDDLValue);

            //CreaMenuIngredienteViewModel newMenu = new CreaMenuIngredienteViewModel(menuingrediente.nombreMenu,menuingrediente.nombreIngrediente);

            _logicaMenuIngredienteExtra.InsertaMenuIngredienteExtra(idMenu, idIngrediente);

            return RedirectToAction("Index");
            //return RedirectToAction("Index");
        }
    }
}

Web_NaturalFood/WebApplicationMVC3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Natural Food", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Categorias", "Index", "Categorias")</li>
                    <li>@Html.ActionLink("Menus", "Index", "Menus")</li>
                    <li>@Html.ActionLink("Ingredientes", "Index", "Ingredientes")</li>
                    <li>@Html.ActionLink("Menus con Ingredientes", "Index", "MenuIngrediente")</li>
                    <li>@Html.ActionLink("IngredientesExtra", "Index", "IngredientesExtras")</li>
                    <li>@Html.ActionLink("Menus con Ingredientes Extra", "Index", "MenuIngredienteExtra")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ONK</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>